name: Run tests

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.11.6"
      - name: Set up virtual environment with Python ${{ matrix.python-version }}
        run: uv venv --python ${{ matrix.python-version }}
      - name: Install dependencies
        run: uv sync --group test
      - name: Run tests
        run: uv run pytest --cov --cov-report=
        env:
          COVERAGE_FILE: coverage/coverage-${{ matrix.python-version }}
      - name: Upload coverage files
        uses: actions/upload-artifact@v7
        with:
          name: coverage-${{ matrix.python-version }}
          path: coverage

  coverage-merge:
    needs: [test]
    runs-on: ubuntu-latest
    permissions:
      statuses: write
    steps:
      - uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.11.6"
      - name: Get coverage files
        uses: actions/download-artifact@v8
        with:
          pattern: coverage-*
          path: coverage
          merge-multiple: true
      - run: uvx coverage combine coverage/*
      - name: Create coverage status
        run: |
          coverage="$(uv run coverage report --format=total)"
          state="$([[ "$coverage" = "100.00" ]] && echo "success" || echo "failure")"

          curl -sS --fail-with-body -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
            -d @- <<EOF
          {
            "state": "${state}",
            "context": "coverage",
            "description": "Coverage ${coverage}%",
            "target_url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }
          EOF
      - run: uv run coverage report --fail-under=100

  doctests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.11.6"
      - name: Set up virtual environment with Python ${{ matrix.python-version }}
        run: uv venv --python ${{ matrix.python-version }}
      - name: Install dependencies
        run: uv sync --group docs
      - name: Run doctests
        run: cd docs && uv run make doctest
      - name: Build docs
        run: cd docs && uv run make html
